site_name: Documentação
nav:
  - Home: index.md

  - Supervisor:
    - Gerenciar servidores: supervisor/example.md

  - Gestão de Docentes: 
    - Gerenciar Ocorrências: gestao-docentes/gerenciar-ocorrencias.md

  - Gestão Escolar:
    - Turmas: gestao-escolar/example.md

  - Prestação de Contas:
    - PDDE: 
        - Geral: prestacao-contas/PDDE/PDDE.md
        - Cadastrar PDDE: prestacao-contas/PDDE/criarPDDE.md
        - Pesquisa de Preço:
          - Criar Pesquisa de Preço: prestacao-contas/PDDE/pesquisa-preco/criarPesquisa.md
          - Realizar Pesquisa de Preço: prestacao-contas/PDDE/pesquisa-preco/realizarPesquisa.md
          - Consolidar Pesquisa de Preço: prestacao-contas/PDDE/pesquisa-preco/consolidacaoPesquisa.md
    - APM:
      - Geral:  prestacao-contas/APM/geral.md
      - Atualizar Vigência: prestacao-contas/APM/atualizarVigencia.md
      - Atas : prestacao-contas/APM/atas.md
    - Ofícios e Memorandos: prestacao-contas/oficios-e-memorandos.md
    - Contas Bancárias: prestacao-contas/contas-bancarias.md
    - Programa: prestacao-contas/programa.md
    - Fornecedores: prestacao-contas/fornecedores.md
    

theme:
  name: material
  palette:
    # Tema claro
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Tema escuro
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  logo: assets/logo.png
  favicon: images/favicon.png
  language: pt

plugins:
  - search
  - glightbox

extra:
  generator: false

extra_css:
  - css/extra.css
