site_name: Documentação
nav:
  - Home: index.md

  - Supervisor:
    - Servidores: supervisor/gerenciar-servidores.md
    - Tipos de Abonos: supervisor/gerenciar-tipos-de-abono.md
    - Categoria de Certificado: supervisor/gerenciar-categorias-certificado.md
    - Configurações de Ano Letivo: supervisor/configuracoes-ano-letivo.md
    - Escolas: 
      - Visualizar Escolas: supervisor/escolas/visualizar-escolas.md
      - Cadastrar Escola: supervisor/escolas/cadastrar-escola.md
      - Editar Escola: supervisor/escolas/editar-escola.md
      - Excluir Escola: supervisor/escolas/excluir-escola.md
    - Séries:
      - Visualizar Séries: supervisor/series/visualizar-series.md
      - Cadastrar Série: supervisor/series/cadastrar-serie.md
      - Editar Série: supervisor/series/editar-serie.md
      - Excluir Série: supervisor/series/excluir-serie.md
      - Ordenar Séries: supervisor/series/ordenar-series.md
    

  - Gestão de Docentes:
    - Ocorrências: gestao-docentes/gerenciar-ocorrencias.md
    - Títulos: gestao-docentes/gerenciar-titulos.md
    - Pontuações: gestao-docentes/gerenciar-pontuacoes.md
    - Tabelas de Vencimento: gestao-docentes/tabela-de-vencimento.md
    - Quinquênio: gestao-docentes/quinquenio.md
    - Classificação de Atribuição de Aulas: gestao-docentes/classificacao.md

  - Gestão Escolar:
    - Alunos: 
      - Visualizar Alunos: gestao-escolar/alunos/visualizar-alunos.md
      - Cadastrar Aluno: gestao-escolar/alunos/cadastrar-aluno.md 
      - Editar Aluno: gestao-escolar/alunos/editar-aluno.md
      - Excluir Aluno: gestao-escolar/alunos/excluir-aluno.md
      - Realizar Matrícula: gestao-escolar/alunos/realizar-matricula.md
      - Visualizar Respostas de Formulários: gestao-escolar/alunos/visualizar-formularios.md
      - Visualizar ou Anexar Documentos: gestao-escolar/alunos/documentos.md
    - Matrículas:
      - Realizar Matrícula: gestao-escolar/matriculas/realizar-matricula.md
    - Turmas:
      - Visualizar Turmas: gestao-escolar/turmas/visualizar-turmas.md
      - Cadastrar Turma: gestao-escolar/turmas/cadastrar-turma.md
      - Editar Turma: gestao-escolar/turmas/editar-turma.md
      - Excluir Turma: gestao-escolar/turmas/excluir-turma.md
      - Realizar Rematrícula: gestao-escolar/turmas/realizar-rematricula.md
      - Realizar Matrícula: gestao-escolar/turmas/realizar-matricula.md
      - Detalhar Turma: gestao-escolar/turmas/detalhar-turma.md
    - Relatórios: 
      - Alunos por Bairro: gestao-escolar/relatorios/alunos-bairro.md
      - Beneficiários do Bolsa Família: gestao-escolar/relatorios/beneficiarios.md
      - Distribuição Racial: gestao-escolar/relatorios/distribuicao-racial.md
      - Meninos e Meninas: gestao-escolar/relatorios/meninos-meninas.md
      - Nível de Conhecimento: gestao-escolar/relatorios/nivel-conhecimento.md
      - Transporte Escolar: gestao-escolar/relatorios/transporte-escolar.md
    - Calendário Acadêmico: 
      - Acessar Calendário Acadêmico: gestao-escolar/calendario/calendario.md
    - Formulários:
      - Visualizar Formulários: gestao-escolar/formularios/visualizar-formularios.md
      - Cadastrar Formulário: gestao-escolar/formularios/cadastrar-formulario.md
      - Editar Formulário: gestao-escolar/formularios/editar-formulario.md
      - Excluir Formulário: gestao-escolar/formularios/excluir-formulario.md
      - Detalhar Formulário: gestao-escolar/formularios/detalhar-formulario.md
      - Visualizar Respostas: gestao-escolar/formularios/visualizar-respostas.md


  - Prestação de Contas:
    - PDDE: 
        - Geral: prestacao-contas/PDDE/PDDE.md
        - Cadastrar PDDE: prestacao-contas/PDDE/criarPDDE.md
        - Pesquisa de Preço:
          - Criar Pesquisa de Preço: prestacao-contas/PDDE/pesquisa-preco/criarPesquisa.md
          - Realizar Pesquisa de Preço: prestacao-contas/PDDE/pesquisa-preco/realizarPesquisa.md
          - Consolidar Pesquisa de Preço: prestacao-contas/PDDE/pesquisa-preco/consolidacaoPesquisa.md
        - Documentos: prestacao-contas/PDDE/documento.md
    - APM:
      - Geral:  prestacao-contas/APM/geral.md
      - Atualizar Vigência: prestacao-contas/APM/atualizarVigencia.md
      - Atas : prestacao-contas/APM/atas.md
      - Ofícios e Memorandos: prestacao-contas/APM/oficios-e-memorandos.md
    - Contas Bancárias: prestacao-contas/contas-bancarias.md
    - Programas: prestacao-contas/programa.md
    - Fornecedores: prestacao-contas/fornecedores.md
    

theme:
  name: material
  palette:
    # Tema claro
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Tema escuro
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  logo: assets/logo.png
  favicon: images/favicon.png
  language: pt

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - search
  - glightbox

extra:
  generator: false

extra_css:
  - css/extra.css